### ISSUE TITLE
contents: Rust crates.io 索引镜像 zju 选项镜像链接错误

### ISSUE THREAD

**Issue by pizeroLOL** [mirrorz-org/mirrorz-help#117]
### 帮助页面的链接（Help page URL）

https://help.mirrorz.org/crates.io-index.git/

### 原文 (Text)

https://help.mirrorz.org/crates.io-index.git/

```toml
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "https://mirrors.zju.edu.cn/crates.io"
```

### 反馈和修正 (Feedback)

https://mirrors.zju.edu.cn/docs/crates.io-index.git/ 

```toml
[source.crates-io]
replace-with = 'zju'

[source.zju]
registry = "https://mirrors.zju.edu.cn/git/crates.io-index.git"
```
