### ISSUE TITLE
contents: 配置清华源后, 在安装package时, 仍然访问repo.anaconda.com

### ISSUE THREAD

**Issue by showintime** [mirrorz-org/mirrorz-help#144]
### 帮助页面的链接（Help page URL）

[https://help.mirrors.cernet.edu.cn/anaconda/](url)

### 原文 (Text)

``` yaml
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

### 反馈和修正 (Feedback)

![image](https://github.com/mirrorz-org/mirrorz-help/assets/29477247/789a6457-6ad5-480e-844a-cc83b61e1577)
我配置了condarc, 但似乎在安装时仍然访问了repo.anaconda.com
这是conda本身的问题嘛, 还是源配置出现了问题?
